### ISSUE TITLE
Lirical post processing error

### ISSUE THREAD

**Issue by tmyates** [yaseminbridges/pheval.lirical#4]
Hello,

I get this error when using the lirical runner, the tsv files are generated but pheval doesn't process. Can you help please? 

... line 133, in create_standardised_results
   ...  lirical_result = read_lirical_result(result)

polars.exceptions.ComputeError: could not parse `1,000` as dtype `i64` at column 'rank' (column number 1)

The current offset in the file is 302 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `1,000` to the `null_values` list.

**Comment by yaseminbridges** [comment]
Hi @tmyates,

I have implemented a fix for this (version 0.2.1), please let me know if it fixes the issue on your end

**Comment by tmyates** [comment]
Thanks very much for your response. I'm using 0.2.1 and now get this? I've looked at raw_results and they seem ok

post processing
...creating pheval results format...
[2025-12-11 12:50:45] [INFO] [phenopacket_utils.py:164] - Creating gene identifier map.

lib/python3.11/site-packages/pheval_lirical/post_process/post_process_results_format.py", line 20, in read_lirical_result
    return pl.read_csv(
           ^^^^^^^^^^^^

/lib/python3.11/site-packages/polars/io/csv/functions.py", line 697, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
           ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: could not parse `-∞` as dtype `f64` at column 'compositeLR' (column number 6)

The current offset in the file is 479 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `-∞` to the `null_values` list.

Original error: ```invalid primitive value found during CSV parsing```

**Comment by yaseminbridges** [comment]
I've now added some handling with the infinity values in 0.2.2 - hopefully this rectifies this problem!

**Comment by tmyates** [comment]
Thanks! but I still get: polars.exceptions.InvalidOperationError: conversion from `str` to `f64` failed in column 'compositeLR' for 7 out of 13 values: ["-∞", "-∞", … "-∞"]

I have tried this and seems to work? 
def extract_disease_results(raw_result: pl.DataFrame) -> pl.DataFrame:
    return raw_result.select(
        [
            pl.col("diseaseCurie").alias("disease_identifier"),
            pl.when(pl.col("compositeLR").cast(pl.Utf8).is_in(["-∞", "−∞"]))
             .then(pl.lit(float("-inf")))
             .otherwise(pl.col("compositeLR").cast(pl.Float64, strict=False))
             .alias("score"),
        ]
    )

**Comment by yaseminbridges** [comment]
Sorry about that! Should be working now with 0.2.3

**Comment by tmyates** [comment]
Thanks all working now!
